// src/utils/delivery.js — Deliver channel invite links to student upon approval
import { CHANNELS, ANNOUNCEMENTS_CHANNEL, PLAN_LABELS } from "../../config.js";
import { escapeMd } from "./helpers.js";
import { logger } from "./logger.js";

// The single-use private invite link — pre-generated by admin (set in .env or hardcoded here)
// This is sent directly to the student instead of generating a new one each time.
const PRIVATE_INVITE_LINK = "https://t.me/+NPn5oPw8e7cxOWE0";

async function createInviteLink(telegram, channelId) {
  if (!channelId || String(channelId).includes("YOUR_") || String(channelId).includes("1234567890")) {
    return null;
  }
  try {
    const expireDate = Math.floor(Date.now() / 1000) + 48 * 3600;
    const link = await telegram.createChatInviteLink(channelId, {
      member_limit: 1,
      expire_date: expireDate,
      name: `CSH Tutorial Access`,
    });
    return link.invite_link;
  } catch (err) {
    logger.warn(`Could not create invite link for channel ${channelId}: ${err.message}`);
    return null;
  }
}

export async function deliverAccess(telegram, order) {
  const { telegram_id, plan, name, order_code } = order;

  // Try to generate a fresh invite link; fall back to the pre-set link
  const channelId = CHANNELS.sem1; // we only have one channel
  let inviteLink = await createInviteLink(telegram, channelId);
  if (!inviteLink) {
    inviteLink = PRIVATE_INVITE_LINK;
  }

  const planLabel = PLAN_LABELS[plan];
  const mainChannel = ANNOUNCEMENTS_CHANNEL;

  const accessMsg =
    `🎉 *Access Granted!*\n` +
    `👋 Hi ${escapeMd(name)}! Welcome to the CSH Tutorial family! 🚀\n\n` +
    `📦 Plan: *${planLabel}*\n\n` +
    `📚 *Your Course & Study Access:*\n` +
    `*${planLabel}:*\n` +
    `🔗 [Join Private Telegram Channel](${inviteLink}) (single-use link, so join quickly!)\n\n` +
    `📢 Stay updated: [Main Channel](${mainChannel})\n\n` +
    `If you have any questions or need help, feel free to contact @Umeribnukedir.`;

  await telegram.sendMessage(telegram_id, accessMsg, { parse_mode: "Markdown" });
  logger.info(`Access delivered to ${telegram_id} for order ${order_code}`);
}
