// src/utils/delivery.js — Deliver channel invite links to student upon approval
import { CHANNELS, ANNOUNCEMENTS_CHANNEL, PLAN_LABELS, QUIZ_PLATFORM_URL } from "../../config.js";
import { escapeHtml } from "./helpers.js";
import { logger } from "./logger.js";
import { generateQuizToken } from "./token.js";

// The single-use private invite link — pre-generated by admin (set in .env or hardcoded here)
// This is sent directly to the student instead of generating a new one each time.
const PRIVATE_INVITE_LINK = "https://t.me/+NPn5oPw8e7cxOWE0";

async function createInviteLink(telegram, channelId) {
  if (!channelId || String(channelId).includes("YOUR_") || String(channelId).includes("1234567890")) {
    return null;
  }
  try {
    const expireDate = Math.floor(Date.now() / 1000) + 48 * 3600;
    const link = await telegram.createChatInviteLink(channelId, {
      member_limit: 1,
      expire_date: expireDate,
      name: `CSH Tutorial Access`,
    });
    return link.invite_link;
  } catch (err) {
    logger.warn(`Could not create invite link for channel ${channelId}: ${err.message}`);
    return null;
  }
}

export async function deliverAccess(telegram, order) {
  const { telegram_id, plan, name, order_code } = order;

  // Try to generate a fresh invite link; fall back to the pre-set link
  const channelId = CHANNELS.sem1; // we only have one channel
  let inviteLink = await createInviteLink(telegram, channelId);
  if (!inviteLink) {
    inviteLink = PRIVATE_INVITE_LINK;
  }

  const planLabel   = PLAN_LABELS[plan] || plan;
  const mainChannel = ANNOUNCEMENTS_CHANNEL;
  const quizToken   = generateQuizToken(order_code);
  const quizLink    = `${QUIZ_PLATFORM_URL}?order=${encodeURIComponent(order_code)}&token=${quizToken}`;

  const isLocal     = QUIZ_PLATFORM_URL.includes("localhost") || QUIZ_PLATFORM_URL.includes("127.0.0.1");

  const quizSection = isLocal
    ? `👉 <b>Take Chapter Quizzes on Web:</b>\n<code>${quizLink}</code>\n`
    : `👉 <a href="${quizLink}">Take Chapter Quizzes on Web (Click to Open)</a>\n`;

  const accessMsg =
    `🎉 <b>Payment Approved &amp; Access Granted!</b>\n` +
    `👋 Welcome <b>${escapeHtml(name)}</b> to the CSH Tutorial family! 🚀\n\n` +
    `📦 Enrolled Plan: <b>${escapeHtml(planLabel)}</b>\n\n` +
    `━━━━━━━━━━━━━━━━━━━━\n` +
    `📚 <b>1. Course Channel Access:</b>\n` +
    `🔗 <a href="${inviteLink}">Join Private Telegram Channel</a>\n` +
    `<i>(⚠️ This is your personal single-use link. Please tap and join immediately!)</i>\n\n` +
    `━━━━━━━━━━━━━━━━━━━━\n` +
    `📝 <b>2. Chapter Quizzes (1,185 Questions):</b>\n` +
    `When you finish studying each chapter, test your mastery with authentic university questions and detailed explanations!\n\n` +
    `👉 <b>How to start taking quizzes:</b>\n` +
    `Type <b>/quiz</b> (or tap the button below). You will be given the choice to practice:\n` +
    `• <b>🤖 In Telegram:</b> Practice right here in chat with interactive buttons.\n` +
    `• <b>🌐 On Web Platform:</b> Practice on full interactive web interface.\n\n` +
    `🔑 <b>Order Verification Code:</b> <code>${escapeHtml(order_code)}</code>\n` +
    `<i>ℹ️ <b>Why is this code used?</b> This is your unique proof of subscription. If you choose to practice quizzes on our website from a computer or browser, enter this code to unlock all chapters and full explanations.</i>\n\n` +
    `━━━━━━━━━━━━━━━━━━━━\n` +
    `📢 Main Channel: <a href="${mainChannel}">CSH Announcements</a>\n\n` +
    `💬 Need assistance? Message @Umeribnukedir directly anytime.`;

  const keyboard = {
    inline_keyboard: [
      [
        { text: "📝 Start Quizzes Now (/quiz)", callback_data: "tgquiz_launch_fresh" }
      ]
    ]
  };

  await telegram.sendMessage(telegram_id, accessMsg, {
    parse_mode: "HTML",
    reply_markup: keyboard,
  });
  logger.info(`Access delivered to ${telegram_id} for order ${order_code}`);
}
